/* Import necessary types and components from Next.js */
import type { Metadata } from "next";
/* Import custom Google Fonts (Geist Sans and Geist Mono) */
import { Geist, Geist_Mono } from "next/font/google";
/* Import global styles */
import "./globals.css";

/* Configure Geist Sans font with Latin subset */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/* Configure Geist Mono (monospace) font with Latin subset */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* Define metadata for the application */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* Root layout component that wraps all pages
 * This component provides the basic HTML structure and applies fonts
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} /* Apply font variables and smooth text rendering */
      >
        {children}
      </body>
    </html>
  );
}
